---
- name: Test if cURL exists as many systems already have it
  command:  command -v curl
  register: curl_exists
  ignore_errors: yes

- name: Install cURL
  include: install.yml
  when: curl_exists.failed is defined and curl_exists.failed
...
